services:
    littlelink:
        build: .
        restart: unless-stopped
        command: npm run start
        ports:
            - "127.0.0.1:8000:8000"
        container_name: littlelink

networks:
    default:
        external: true
        name: proxypool
